spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true # sql문 보기
        format_sql: true # sql문 예쁘게 보기



  security:
    jwt:
      secret: ${jwt.secret}
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client}
            client-secret: ${kakao.client.secret}
            redirect-uri: http://localhost:8080/kakao/callback
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: kakao
          google:
            client-id: ${google.client}
            client-secret: ${google.client.secret}
            redirect-uri: http://localhost:8080/google/callback
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 300MB

cloud:
  aws:
    s3:
      bucket: aboutme-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${aws.s3.accesskey}
      secretKey: ${aws.s3.secretkey}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
